// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RedSocial.Server.Data;

#nullable disable

namespace RedSocial.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RedSocial.Shared.Models.Amigo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaAmigos")
                        .HasColumnType("datetime2");

                    b.Property<int>("MiPerfilId")
                        .HasColumnType("int");

                    b.Property<int>("PerfilAmigoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MiPerfilId");

                    b.HasIndex("PerfilAmigoId");

                    b.ToTable("Amigos");
                });

            modelBuilder.Entity("RedSocial.Shared.Models.Generos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("RedSocial.Shared.Models.Historia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("PerfilCreacionId")
                        .HasColumnType("int");

                    b.Property<string>("TextoHistoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PerfilCreacionId");

                    b.ToTable("Historias");
                });

            modelBuilder.Entity("RedSocial.Shared.Models.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Biografia")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoPerfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GeneroId");

                    b.ToTable("Perfiles");
                });

            modelBuilder.Entity("RedSocial.Shared.Models.Respuesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaRespuesta")
                        .HasColumnType("datetime2");

                    b.Property<int>("HistoriaId")
                        .HasColumnType("int");

                    b.Property<int>("PerfilRespuestaId")
                        .HasColumnType("int");

                    b.Property<string>("TextoRespuesta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("HistoriaId");

                    b.HasIndex("PerfilRespuestaId");

                    b.ToTable("Respuestas");
                });

            modelBuilder.Entity("RedSocial.Shared.Models.SolicitudAmistad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aceptado")
                        .HasColumnType("bit");

                    b.Property<bool>("AceptarMensajes")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PerfilSolicitaId")
                        .HasColumnType("int");

                    b.Property<int>("PerfilSolicitadoId")
                        .HasColumnType("int");

                    b.Property<int>("PerfilSolictaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerfilSolicitaId");

                    b.HasIndex("PerfilSolicitadoId");

                    b.ToTable("SolicitudesAmistad");
                });

            modelBuilder.Entity("RedSocial.Shared.Models.Amigo", b =>
                {
                    b.HasOne("RedSocial.Shared.Models.Perfil", "MiPerfil")
                        .WithMany()
                        .HasForeignKey("MiPerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RedSocial.Shared.Models.Perfil", "PerfilAmigo")
                        .WithMany()
                        .HasForeignKey("PerfilAmigoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MiPerfil");

                    b.Navigation("PerfilAmigo");
                });

            modelBuilder.Entity("RedSocial.Shared.Models.Historia", b =>
                {
                    b.HasOne("RedSocial.Shared.Models.Perfil", "PerfilCreacion")
                        .WithMany()
                        .HasForeignKey("PerfilCreacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilCreacion");
                });

            modelBuilder.Entity("RedSocial.Shared.Models.Perfil", b =>
                {
                    b.HasOne("RedSocial.Shared.Models.Generos", "Genero")
                        .WithMany()
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("RedSocial.Shared.Models.Respuesta", b =>
                {
                    b.HasOne("RedSocial.Shared.Models.Historia", "Historia")
                        .WithMany()
                        .HasForeignKey("HistoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RedSocial.Shared.Models.Perfil", "PerfilRespuesta")
                        .WithMany()
                        .HasForeignKey("PerfilRespuestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Historia");

                    b.Navigation("PerfilRespuesta");
                });

            modelBuilder.Entity("RedSocial.Shared.Models.SolicitudAmistad", b =>
                {
                    b.HasOne("RedSocial.Shared.Models.Perfil", "PerfilSolicita")
                        .WithMany()
                        .HasForeignKey("PerfilSolicitaId");

                    b.HasOne("RedSocial.Shared.Models.Perfil", "PerfilSolicitado")
                        .WithMany()
                        .HasForeignKey("PerfilSolicitadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilSolicita");

                    b.Navigation("PerfilSolicitado");
                });
#pragma warning restore 612, 618
        }
    }
}
